### ISSUE TITLE
Helm template issue 

### ISSUE THREAD

**Issue by eyesoftsys** [Leaseweb/cloudstack-csi-driver#145]
Please fix helm template : 

`Error: YAML parse error on cloudstack-csi/templates/syncer-job.yaml: error converting YAML to JSON: yaml: line 24: did not find expected node content
`

https://github.com/Leaseweb/cloudstack-csi-driver/blob/master/charts/cloudstack-csi/templates/syncer-job.yaml#L22

![image](https://github.com/user-attachments/assets/8e42350e-91f5-441d-852b-5730eab5d6dd)

**Comment by hrak** [comment]
Hi @eyesoftsys thank you for reporting this issue. This has been addressed in the latest release of the chart.
