### ISSUE TITLE
Resize pvc feature

### ISSUE THREAD

**Issue by mierea** [Leaseweb/cloudstack-csi-driver#56]
Hello,

Any idea if resizing pvc works on this fork? 
If not, is it by any chance planned in the future?

PS: thanks for working on this, it works very nicely!

**Comment by hrak** [comment]
Not yet, but it is something we will work on in the near future!

**Comment by hrak** [comment]
This is now implemented in [v0.3.0](https://github.com/Leaseweb/cloudstack-csi-driver/releases/tag/v0.3.0). Thanks for the feedback!
